name: Sync Fork

on:
  schedule:
    - cron: '0 3 * * *' # Executa diariamente às 3h
  workflow_dispatch: # Permite executar manualmente

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Fork
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Desativa as credenciais padrão para usar o token

      - name: Set Git Config
        run: |
          git config --global user.email "jonatassilvaperaza@gmail.com"
          git config --global user.name "jonatasperaza"

      - name: Add Upstream
        run: git remote add upstream https://github.com/HackHeaders/FrontEnd.git

      - name: Fetch Upstream
        run: git fetch upstream

      - name: Merge Upstream into Fork
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories

      - name: Push Changes
        run: |
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git main
